export const projects = [
  {
    id: '1',
    screenshot: 'https://opengraph.githubassets.com/1/JanithPer/impact-workshop-management',
    images: [
      '/impact-workshop-management/IWM ss (1).png',
      '/impact-workshop-management/IWM ss (2).png',
      '/impact-workshop-management/IWM ss (3).png',
      '/impact-workshop-management/IWM ss (4).png',
      '/impact-workshop-management/IWM ss (5).png',
      '/impact-workshop-management/IWM ss (6).png',
      '/impact-workshop-management/IWM ss (7).png',
      '/impact-workshop-management/IWM ss (8).png',
      '/impact-workshop-management/IWM ss (9).png',
      '/impact-workshop-management/IWM ss (10).png',
      '/impact-workshop-management/IWM ss (11).png',
      '/impact-workshop-management/IWM ss (12).png',
      '/impact-workshop-management/IWM ss (13).png',
      '/impact-workshop-management/IWM ss (14).png',
      '/impact-workshop-management/IWM ss (15).png',
      '/impact-workshop-management/IWM ss (16).png',
      '/impact-workshop-management/IWM ss (17).png',
      '/impact-workshop-management/IWM ss (18).png',
      '/impact-workshop-management/IWM ss (19).png',
    ],
    title: 'Impact Workshop Management',
    subTitle: 'Workshop management platform',
    stack: ['next.js', 'typescript', 'tailwindcss', 'node.js', 'express', 'mongodb'],
    description:
      'Impact Workshop Management is a workshop operations app built to organize workshop schedules, participant registrations, and administrative workflows in one place. It focuses on keeping event data structured, making it easier to manage sessions, attendees, and planning tasks from a single interface.',
    date: 'Open source project',
    github: 'https://github.com/JanithPer/impact-workshop-management',
    live: '',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: 'https://opengraph.githubassets.com/1/Nipuna-Lakruwan/codemiZe',
    images: [
      '/codemize/codemise (1).jpeg',
      '/codemize/codemise (2).jpeg',
      '/codemize/codemise (3).jpeg',
      '/codemize/codemise (4).jpeg',
      '/codemize/codemise (5).jpeg',
      '/codemize/codemise (6).jpeg',
      '/codemize/codemise (7).jpeg',
      '/codemize/codemise (8).jpeg',
      '/codemize/codemise (9).jpeg',
    ],
    title: 'CodemiZe',
    subTitle: 'Coding event and learning platform',
    stack: ['react', 'typescript', 'tailwindcss', 'node.js', 'express', 'firebase'],
    description:
      'CodemiZe is a coding-focused platform centered around events, learning content, and community engagement. The project presents a clean way to showcase coding initiatives and help users explore programming-related activities in a structured experience.',
    date: 'Open source project',
    github: 'https://github.com/Nipuna-Lakruwan/codemiZe',
    live: '',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '3',
    screenshot: 'https://opengraph.githubassets.com/1/JanithPer/real-time-chat',
    images: [
      '/codemize/codemise (1).jpeg',
      '/codemize/codemise (2).jpeg',
      '/codemize/codemise (3).jpeg',
      '/codemize/codemise (4).jpeg',
      '/codemize/codemise (5).jpeg',
      '/codemize/codemise (6).jpeg',
      '/codemize/codemise (7).jpeg',
      '/codemize/codemise (8).jpeg',
      '/codemize/codemise (9).jpeg',
    ],
    title: 'Real Time Chat',
    subTitle: 'Real-time messaging app',
    stack: ['react', 'typescript', 'node.js', 'express', 'socket.io', 'mongodb'],
    description:
      'Real Time Chat is a messaging application designed for instant conversations with live updates, online presence, and persistent chat history. It demonstrates the core pieces of a modern chat experience, including fast message delivery and a responsive interface.',
    date: 'Open source project',
    github: 'https://github.com/JanithPer/real-time-chat',
    live: '',
    color: 'rgba(79,70,229)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '4',
    screenshot: 'https://opengraph.githubassets.com/1/JanithPer/inventory-V1',
    images: [
      '/inventory-management-system/Inventory screenshot (1).png',
      '/inventory-management-system/Inventory screenshot (2).png',
      '/inventory-management-system/Inventory screenshot (3).png',
      '/inventory-management-system/Inventory screenshot (4).png',
      '/inventory-management-system/Inventory screenshot (5).png',
    ],
    title: 'Inventory V1',
    subTitle: 'Inventory management system',
    stack: ['react', 'typescript', 'node.js', 'express', 'mongodb', 'mongoose'],
    description:
      'Inventory V1 is an inventory management app built to help track products, stock levels, and item movement more efficiently. It is structured around the basic workflows needed to manage inventory data and keep business records organized.',
    date: 'Open source project',
    github: 'https://github.com/JanithPer/inventory-V1',
    live: '',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  {
    id: '5',
    screenshot: 'https://opengraph.githubassets.com/1/JanithPer/subscription-tracker-api',
    images: [
      '/inventory-management-system/Inventory screenshot (1).png',
      '/inventory-management-system/Inventory screenshot (2).png',
      '/inventory-management-system/Inventory screenshot (3).png',
      '/inventory-management-system/Inventory screenshot (4).png',
      '/inventory-management-system/Inventory screenshot (5).png',
    ],
    title: 'Subscription Tracker API',
    subTitle: 'Subscription tracking API',
    stack: ['node.js', 'express', 'typescript', 'postgresql', 'jwt', 'rest api'],
    description:
      'Subscription Tracker API is a backend service for managing subscription records, renewal dates, and payment-related tracking. It is suited for building tools that need a structured API around recurring plans and account lifecycle management.',
    date: 'Open source project',
    github: 'https://github.com/JanithPer/subscription-tracker-api',
    live: '',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  },
];
